title:              Clean Blog
email:              sunguk123456@gmail.com
description:        A Blog Theme by Start Bootstrap
baseurl:            "l"
url:                "https://sunguk.github.io"

# Social Profiles

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
